#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2019/10/29 0:37
# @Auther  : Peach
# @File    : 6001.py
#写函数，用户传入修改的文件名与要修改的内容，执行函数，完成修改操作
def modify_files(file_name,old_content,new_content):
    import os
    with open(file_name,'rt',encoding='utf-8') as read_f,open('%s.swap'%file_name,'wt',encoding='utf-8') as write_f:
        for line in read_f:
            if old_content in line:
                line.replace(old_content,new_content)
            write_f.write(line)
    os.remove(file_name)
    os.rename('%s.swap'%file_name,file_name)
    

#写函数，计算传入字符串中【数字】、【字母】、【空格] 以及 【其他】的个数
def count(statement):
    dict_count={'alpha':0,'number':0,'space':0,'others':0}
    for i in statement:
        if i.isalpha:
            dict_count['alpha']+=1
        elif i.isdigit:
            dict_count['count']+=1
        elif i==' ':
            dict_count['space']+=1
        else:
            dict_count['others']+=1
    return dict_count
    
    
#写函数，判断用户传入的对象（字符串、列表、元组）长度是否大于5
def judge_5(content):
    if len(content)>5:
        return True
    else:
        return False
        
        
#写函数，检查传入列表的长度，如果大于2，那么仅保留前两个长度的内容，并将新内容返回给调用者
def length_of_list(content):
    if len(content)>2:
        return content[:2]
        
        
#写函数，检查获取传入列表或元组对象的所有奇数位索引对应的元素，并将其作为新列表返回给调用者
def get_odd_index(content):
    odd_index=[]
    for i in content:
        if content.index(i)%2:
            odd_index.append(i)
    return odd_index
    
    
#写函数，检查字典的每一个value的长度,如果大于2，那么仅保留前两个长度的内容，并将新内容返回给调用者
def check_value(dict):
    for key,value in dict.items():
        if len(value)>2:
            dict[key]=value[:2]
    return dict
